FROM golang:1.12.1

LABEL maintainer="Masato Yamazaki <mas9612@gmail.com>"

RUN mkdir -p /go/src/github.com/mas9612/nwspeaker
COPY . /go/src/github.com/mas9612/nwspeaker

WORKDIR /go/src/github.com/mas9612/nwspeaker

CMD ["./scripts/run_test.sh"]
